### ISSUE TITLE
textadept w/tatoolbar crashes/hangs if filename contains characters outside US-ASCII set

### ISSUE THREAD

**Issue by gibboni** [gabdub/ta-tweaks#1]
To reproduce the problem: create a file which name has at least one character outside US-ASCII set, for example latin small letter 'a' with diaeresis (U+00E4 / 0x84) : test_file_ä.txt

When the file is opened, tatoolbar's tab/buffer label for the file is empty, only the button to close the tab is there. The file itself is loaded fully. If textadept did not crash at this point, opening another similarly named file will make it hang or crash.

I used the latest versions (from hg and git repos) of both textadept and tatoolbar. I have all your additional modules installed but nothing extra for textadept. I have cross compiled textadept on linux for Windows (10). 

I have not had the time to test this on linux because I have only a console access to the build server I use.

**Comment by gabdub** [comment]
Thanks for the report!
Please check the last commit.

**Comment by gibboni** [comment]
Thank you for the quick response! Now everything works if the file is loaded via textadept's File-menu. But if the file is loaded from the command line it will still crash textadept. It requires textadept to be already started.

By the way, tatoolbar is great! This is something I've been wanting textadept to have ever since I started using it. :)

**Comment by gabdub** [comment]
Thanks for your kind words.
At first, the file opens OK on my Win32 machine... I'll continue testing it later.
I also noticed that drag and drop does not work with filenames like this, but I think it's a textadept issue.

**Comment by gabdub** [comment]
Running TA9.5+tatoolbar on Win7 and all the things l tried worked fine  (for example: textadept ññññ.txt áéíóú.txt)
Have you tried plain textadept 9.5 to see if the problem is still there?

**Comment by gibboni** [comment]
Just tested with plain textadept 9.5. If I load two files together in a single command, it works. But when the file's are loaded one at a time, then the second one crashes it. So it seems that the issue with tatoolbar is now fixed and the remaining problem is a textadept issue.

**Comment by gabdub** [comment]
OK. Let me know if you find something else.
