### ISSUE TITLE
Error loading keys_osx.lua

### ISSUE THREAD

**Issue by Nanoc-ice** [gabdub/ta-tweaks#10]
I am trying to get your project view module working (without re-compiling) and when adding the toolbar modules and then running textadept, I get the following error when loading keys_osx.lua:

...keys_osx.lua:409: '}' expected (to close '{' at line 227) near '"del_word_left"'

I am looking to get the project buffer and don't need the toolbar yet.  Saying that, this is what I have as requires for this module in my .textadept/init.lua:

require('util')
require('export')
require('project')
require('toolbar')

Granted I don't know if that is correct as there really isn't clear steps to follow.

**Comment by Nanoc-ice** [comment]
That problem is corrected by added a comma at the end of line of 406.  And then there are 2 "end" at 415 and 416.  
Then that leads to the error:
keys_osx.lua:420: attempt to get length of a nil value (local 'lst')

That error is from the default_accelerators being defined local within the if/else

**Comment by gabdub** [comment]
Thanks for the report. I'll fix it asap.
Keep in mind that I did not test the OSX version because I do not have an osx system.
