### ISSUE TITLE
Unable to toggle comment

### ISSUE THREAD

**Issue by brynne8** [gabdub/ta-tweaks#11]
When I try to use <kbd>Ctrl</kbd>+<kbd>/</kbd> to toggle comment, the Console Ouput shows:
```
...rs\Alexander Misel/.textadept/modules/textadept\keys.lua:351: No Localization:Unknown command: toggle_comment
```
In addition, it will be better if I can double click to open the file on Console Output.

**Comment by gabdub** [comment]
Thanks for the report. TA11 was a massive change.

fixed: block_comment renamed toggle_comment in TA11
https://github.com/gabdub/ta-tweaks/commit/2d207eaf942327a68c9bc65517062b6fad5d1835

You can also use Alt+7 to toggle comments at the beginning of lines (see quicktype module).
