### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by brynne8** [gabdub/ta-tweaks#12]
There seems to be some problems with the tatoolbar scrollbars. One of the problems is that when I turn off the "Replace vertical toolbar", it seems that instead of closing it, two scrollbars appear at the same time.

For shorter files (but more than one screen), the scrollbar does not scroll to the bottom.
For shorter files, less than one screen, there is no need to show a scrollbar, but a scrollbar is shown anyway, making it look like there is content below.
For very long files, the scrollbar is too short, making it difficult to drag the scrollbar with the mouse.

In addition, I also felt that the scrollbar didn't drag very smoothly, and I don't know if it was just an illusion on my part.

**Comment by gabdub** [comment]
Have you tried "apply changes" and closing and reopening TA?
TA sometimes require a complete reset to remove the scroll bars.

Minimap is a bit different than a scroll bar.
It uses fixed height boxes to represent points in the buffer. 2 white boxes mark the beginning and end of the file. When the file is big enough this marks don't move any more and a box represent more than one line.
When you click a box the soft try to center that line in the screen. Drag is kind of a continuous clicking. Try dragging up or down when you reach the top or the bottom and you will see that the scroll bar doesn't move but the current line changes.

**Comment by brynne8** [comment]
Thank you for your explanation. As the minimap doesn't look like the same thing in other editors,
![atom_minimap](https://raw.githubusercontent.com/atom-minimap/minimap/master/resources/with-code-highlights.png)
I didn't realize it was minimap
