### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by brynne8** [gabdub/ta-tweaks#13]
- In console output, I prefer a box that can select freely instead of line by line. Resizing the console ouput pane is not easy either.
- When encounter an error, I want to be able to double-click on the error to locate the corresponding location of the code directly.
- Copy and paste can sometimes be problematic. Sometimes the things copied inside Textadept can't be pasted outside.
- The project panel I want to be able to see the tree structure of the files like a file browser, right-clicking on files or folders can open it in explorer; freely add and delete files in this panel without switching to another window

**Comment by gabdub** [comment]
Regarding point 1, have you tried "USE_RESULTS_PANEL=false" in init.lua?
The buffer version allows you to select text and resize it freely.

Thanks for your suggestions.

**Comment by gabdub** [comment]
I have implemented points 2 and 4 and will be available when TA 11.2 is released.
Regarding the copy/paste issue, this may be a TA or Scintilla problem. I'm not sure how to reproduce it.
