### ISSUE TITLE
Error shown after startup

### ISSUE THREAD

**Issue by juh2** [gabdub/ta-tweaks#3]
When I start up textadept with the project module I get this error message.

/home/juh/.textadept/modules/project/proj_ui.lua:81: bad argument #3 to '__newindex' (number expected, got string)

The module itself is working kind of. I try to figure out which functions work and which not.

**Comment by gabdub** [comment]
The colors properties are loaded in colors.lua which is loaded in the ggg.lua theme using:
`dofile(_USERHOME..'/themes/colors.lua')`

You can set only the properties you need with:
```
local p= buffer.property
p['color.prj_sel_bar_nof']=0x88acdf
p['color.prj_sel_bar']=0xa8ccff
p['color.prj_open_mark']=0x404040
```

**Comment by juh2** [comment]
When I load ggg in init.lua I get an error:

/home/juh/.textadept/modules/project/proj_ui.lua:125: attempt to index a nil value (global 'toolbar')

Maybe it is not recommended to use project module without compiling toolbar?

**Comment by gabdub** [comment]
remove `not toolbar.tbreplvscroll` and left:

`buffer.v_scroll_bar= true`

**Comment by juh2** [comment]
ok. No error messages after startup and it seems to work. Thanks for your super fast reaction.

**Comment by gabdub** [comment]
:)
