### ISSUE TITLE
No SVN/GIT repository set in project

### ISSUE THREAD

**Issue by juh2** [gabdub/ta-tweaks#4]
With your hints I managed to setup the tweaks so far. Project search works, but when I press F6 I get the error message in the status bar:

No SVN/GIT repository set in project

How can I set the git repository? I thought it would automagically find the .git like pure textadept.

**Comment by gabdub** [comment]
You have to a add a line by hand to the project in edit mode.

See `proj_data.lua` for the format (it's a little cryptic, I know... but this way you can connect to more than one repository in a project).

Basically, the path to a file is transformed to a path (to that file) in the repository.

For example:
If the  file `C:\Users\desa1\.textadept\modules\init.lua ` is `modules\init.lua` for the git repository located in `C:\Users\desa1\.textadept\ta-tweaks`, you enter:

`[git]::C:\Users\desa1\.textadept\::`**G,**`C:\Users\desa1\.textadept\ta-tweaks`

(No spaces. "G" for GIT or "S" for SVN).
All files that are inside any of the GIT or SVN directories can be used with `Proj.show_filevcinfo` (SVN/GIT show file info) or `Proj.vc_changes_status` (SVN/GIT: compare to HEAD).

**Comment by juh2** [comment]
I guess that I can add several paths after the "G"?

I inserted this in my project-file:
`{git]::/home/juh/Projekte/Literatur/sphinx-handbuch/::G,/home/juh/Projekte/Literatur/sphinx-handbuch`

I can now compare to HEAD but without highlighting or any other mean to mark the differences.

In command buffer I see this error message:

`/home/juh/.textadept/modules/project/proj_cmd.lua:563: attempt to call a nil value (field 'updateaction')`

**Comment by gabdub** [comment]
You can add multiple GIT or SVN repositories (one per line, the first matching directory is used).
I commited some changes to make actions optional.
