### ISSUE TITLE
Textadapt hangs when calling "make"

### ISSUE THREAD

**Issue by juh2** [gabdub/ta-tweaks#5]
I use textadept and ta-tweaks for writing ConTeXt and Sphinx Documentations.

I use Makefiles that call LuaLaTeX or ConTeXt to build the project. 

When I call the Makefile of a project from within textadept it hangs afters a few lines of compiling, consuming 100% of the cpu.

No problems with pure textadept.

The error occurs as soon as I activate utils and project.

**Comment by gabdub** [comment]
Can you reproduce the issue using a different lexer and running something I can try?

**Comment by juh2** [comment]
I can reproduce the error with a Sphinx project. The first run (compiling html) works. But when I run a longer make command like "make clean html latexpdf epub", generating HTML-, PDF- and EPUB-output it hangs.

**Comment by gabdub** [comment]
I was referring to something I can reproduce :)

If you are running on Windows, try compiling the nightly version (on Sep 10th, Mitchell mention some hungs on Windows related to the old GTK used). 

If you want to give it a try:
* Download the nigthly version in another folder
* compile TA with NIGHTLY=1
* rename the Makefile to something like MakefileOrg
* put tatoolbar/src files in src folder
* check the differences between the Makefiles (normally only some ZIP filename change in nightly)
* adjust the Makefile and compile with tatoolbar with NIGHTLY=1
check: https://foicica.com/textadept/manual.html#Compiling
