### ISSUE TITLE
Option to use custom fontface for tatoolbar

### ISSUE THREAD

**Issue by brynne8** [gabdub/ta-tweaks#9]
It seems tatoolbar doesn't allow us to use a custom font face. But I need to use font that support Chinese characters.

**Comment by gabdub** [comment]
You're right, tatoolbar uses the default system font. At some point I'll see if I can add it. Sorry.

**Comment by brynne8** [comment]
thanks

**Comment by gabdub** [comment]
I added font selection to version tatoolbar 1.1.11 from the configuration panel.
See [font_config.png
](https://github.com/gabdub/ta-tweaks/wiki/img/font_config.png)
Try release TA11.0.1.
Hope this helps.

**Comment by brynne8** [comment]
It works. Thanks a lot.
